name: sarif
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: sarif
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: tfsec
        uses: aquasecurity/tfsec-sarif-action@aca189a325c7daae0664c25f6279de86f6abc1c6
        with:
          sarif_file: tfsec.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif
